homepage:
    path: /
    defaults: { _controller: 'App\Controller\HomeController::index' }

pages.about:
    path: /about
    defaults: { _controller: 'App\Controller\Page\AboutController::index' }

events.next:
    path: /event/next
    defaults: { _controller: 'App\Controller\EventController::next' }

events.past:
    path: /event/past
    defaults: { _controller: 'App\Controller\EventController::past' }

events.event:
    path: /event/{event}
    defaults: { _controller: 'App\Controller\EventController::event' }