homepage:
    path: /
    defaults: { _controller: 'App\Controller\HomeController::index' }

pages.about:
    path: /about
    defaults: { _controller: 'App\Controller\Page\AboutController::index' }

events.index:
    path: /events/
    defaults: { _controller: 'App\Controller\EventsController::index' }

events.next:
    path: /events/next/
    defaults: { _controller: 'App\Controller\EventsController::next' }

events.past:
    path: /events/past/
    defaults: { _controller: 'App\Controller\EventsController::past' }

events.event:
    path: /events/{event}
    defaults: { _controller: 'App\Controller\EventsController::event' }