# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../src/{Entity,Migrations,Repository,Tests}'

    # controllers are imported separately to make sure they
    # have the tag that allows actions to type-hint services
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Content\PageContentRetriever:
        class: App\Content\PageContentRetriever
        arguments:
            - '%kernel.root_dir%/../content/pages'

    League\CommonMark\CommonMarkConverter:
        class: League\CommonMark\CommonMarkConverter

    App\Parser\Markdown\LeagueCommonMarkMarkdownParser:
        class: App\Parser\Markdown\LeagueCommonMarkMarkdownParser
        arguments:
            - '@League\CommonMark\CommonMarkConverter'

    App\Parser\Markdown\MarkdownParser: '@App\Parser\Markdown\LeagueCommonMarkMarkdownParser'

    Psr\SimpleCache\CacheInterface:
        class: Symfony\Component\Cache\Simple\FilesystemCache

    App\Parser\Markdown\CachingMarkdownParser:
        class: App\Parser\Markdown\CachingMarkdownParser
        arguments:
            - '@App\Parser\Markdown\CachingMarkdownParser.inner'
            - '@Psr\SimpleCache\CacheInterface'
        decorates: App\Parser\Markdown\MarkdownParser

    App\Twig\AppExtension:
        class: App\Twig\AppExtension
        arguments:
            - '@App\Parser\Markdown\MarkdownParser'
        tags:
            - twig.extension

    DMS\Service\Meetup\MeetupKeyAuthClient:
        class: DMS\Service\Meetup\MeetupKeyAuthClient
        factory: 'DMS\Service\Meetup\MeetupKeyAuthClient::factory'
        arguments:
            - key: '%env(MEETUP_API_KEY)%'

    App\Meetup\Client\RdohmsClient:
        class: App\Meetup\Client\RdohmsClient
        arguments:
            - '@DMS\Service\Meetup\MeetupKeyAuthClient'
            - '%env(MEETUP_GROUP_NAME)%'

    App\Meetup\Client\CachingClient:
        class: App\Meetup\Client\CachingClient
        arguments:
          - '@App\Meetup\Client\CachingClient.inner'
          - '@Psr\SimpleCache\CacheInterface'
        decorates: App\Meetup\Client\RdohmsClient

    App\Meetup\Client: '@App\Meetup\Client\CachingClient'